# Generated by Django 5.2.4 on 2025-07-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
